name: Destroy Stack using AWS CDK

on: #[push]
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cdk destroy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'destroy'
          cdk_stack: 'HelloWorldStack'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'